apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: portal
  name: portal
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: portal
    spec:
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-portal:v1
        name: piggyback-prod-runner-portal
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
