apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: portal
  name: portal
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 5000
  selector:
    io.kompose.service: portal
status:
  loadBalancer: {}
