version: '3.1'

services:
    location:
        image: piggy1/location:latest
        container_name: piggyback-dev-runner-location-1
        restart: always
        volumes:
        - ./gcp-secret-vol:/app/config
        ports:
         - "8080:8080"
        external_links:
        - piggyback-dev-runner-mongo-1
    offers:
        image: piggy1/offers:latest
        container_name: piggyback-dev-runner-offers-1
        restart: always
        volumes:
        - ./gcp-secret-vol:/app/config
        ports:
         - "8081:8081"
        external_links:
        - piggyback-dev-runner-mongo-1
    events:
        image: piggy1/events:latest
        container_name: piggyback-dev-runner-events-1
        restart: always
        volumes:
        - ./gcp-secret-vol:/app/config
        ports:
         - "8082:8082"
        external_links:
        - piggyback-dev-runner-mongo-1
    user:
        image: piggy1/user:latest
        container_name: piggyback-dev-runner-user-1
        restart: always
        volumes:
        - ./gcp-secret-vol:/app/config
        ports:
         - "8083:8083"
        external_links:
        - piggyback-dev-runner-mysql-1
    invoice:
        image: piggy1/invoice:latest
        container_name: piggyback-dev-runner-invoice-1
        restart: always
        ports:
         - "8084:8084"
        external_links:
        - piggyback-dev-runner-mysql-1
    partner:
        image: piggy1/partner:latest
        container_name: piggyback-dev-runner-partner-1
        restart: always
        volumes:
        - ./gcp-secret-vol:/app/config
        ports:
         - "8085:8085"
        external_links:
        - piggyback-dev-runner-mongo-1
    notification:
        image: piggy1/notification:latest
        container_name: piggyback-dev-runner-notification-1
        restart: always
        volumes:
        - ./gcp-secret-vol:/app/config
        ports:
         - "8086:8086"
    portal:
        image: piggy1/portal:latest
        container_name: piggyback-dev-runner-portal-1
        restart: always
        ports:
         - "5000:5000"
    mongo:
        image: mongo:latest
        container_name: piggyback-dev-runner-mongo-1
        restart: always
        volumes: 
        - mongo-data-vol:/data/db
        - mongo-init-vol:/docker-entrypoint-initdb.d
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express:latest
        container_name: piggyback-dev-runner-mongo-express-1
        restart: always
        ports:
        - "8001:8081"
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
    mysql:
        image: mysql:latest
        container_name: piggyback-dev-runner-mysql-1
        restart: always
        volumes: 
        - ./mysql-data-vol:/var/lib/mysql
        - ./mysql-init-vol:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: 'password'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: piggyback-dev-runner-phpmyadmin-1
        environment:
        - PMA_ARBITRARY=1
        restart: always
        ports:
        - "8000:80"
    sample:
        image: piggy1/sampleapp:latest
        container_name: piggyback-dev-runner-sampleapp-1
        restart: always
        ports:
         - "8087:8080"
        external_links:
        - piggyback-dev-runner-mongo-1
    order:
        image: piggy1/order:latest
        container_name: piggyback-dev-runner-order-1
        restart: always
        volumes:
        - ./gcp-secret-vol:/app/config
        ports:
         - "8088:8080"
        external_links:
        - piggyback-dev-runner-mongo-1
volumes:
    mysql-data-vol:
    mysql-init-vol:
    mongo-data-vol:
    mongo-init-vol:
    gcp-secret-vol: