version: '3.1'

services:
    location:
        image: piggy1/location:latest
        restart: always
        ports:
         - "8080:8080"
        links:
        - mongo
    offers:
        image: piggy1/offers:latest
        restart: always
        ports:
         - "8081:8081"
    events:
        image: piggy1/events:latest
        restart: always
        ports:
         - "8082:8082"
        links:
        - mongo
    user:
        image: piggy1/user:latest
        restart: always
        ports:
         - "8083:8083"
        links:
        - mysql
    invoice:
        image: piggy1/invoice:latest
        restart: always
        ports:
         - "8084:8084"
        links:
        - mysql
    partner:
        image: piggy1/partner:latest
        restart: always
        ports:
         - "8085:8085"
        links:
        - mysql
    notification:
        image: piggy1/notification:latest
        restart: always
        ports:
         - "8086:8086"
    portal:
        image: piggy1/portal:latest
        restart: always
        ports:
         - "3000:3000"
    mongo:
        image: mongo:latest
        restart: always
        volumes: 
        - mongo-data-vol:/data/db
        - mongo-init-vol:/docker-entrypoint-initdb.d
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
        - "8001:8081"
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
    mysql:
        image: mysql:latest
        restart: always
        volumes: 
        - ./mysql-data-vol:/var/lib/mysql
        - ./mysql-init-vol:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_USER: 'test'
          MYSQL_PASS: 'pass'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
        - PMA_ARBITRARY=1
        restart: always
        ports:
        - "8000:80"
volumes:
    mysql-data-vol:
    mysql-init-vol:
    mongo-data-vol:
    mongo-init-vol: