apiVersion: apps/v1
kind: Deployment
metadata:
  name: piggyback-offers-production
  labels:
    app: piggyback-offers
    env: production
  namespace: default
spec:
  replicas: 3
  progressDeadlineSeconds: 10
  selector:
    matchLabels:
      app: piggyback-offers
      env: production
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: piggyback-offers
        env: production
    spec:
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-offers:v1
        name: piggyback-prod-runner-offers
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        restartPolicy: Always
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8081
        livenessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 10
          failureThreshold: 1      
status: {}
