apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: control-center
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: control-center
        env: canary
    spec:
      containers:
      - image: confluentinc/cp-enterprise-control-center:5.3.1
        name: control-center
        env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: "broker:29092"
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        - name: CONFLUENT_METRICS_TOPIC_REPLICATION
          value: "1"
        - name: PORT
          value: "9021"
        resources:
          limits:
            memory: "1Gi"
            cpu: "750m"
        imagePullPolicy: Always
        ports:
        - name: piggy-control
          containerPort: 9021
status: {}
