version: '3.1'

services:
    location:
        image: piggy1/location:latest
        container_name: piggyback-dev-runner-location
        restart: always
        ports:
         - "8080:8080"
    offers:
        image: piggy1/offers:latest
        container_name: piggyback-dev-runner-offers
        restart: always
        ports:
         - "8080:8080"
    events:
        image: piggy1/events:latest
        container_name: piggyback-dev-runner-events
        restart: always
        ports:
         - "8080:8080"
    user:
        image: piggy1/user:latest
        container_name: piggyback-dev-runner-user
        restart: always
        ports:
         - "8080:8080"
    invoice:
        image: piggy1/invoice:latest
        container_name: piggyback-dev-runner-invoice
        restart: always
        ports:
         - "8080:8080"
    partner:
        image: piggy1/partner:latest
        container_name: piggyback-dev-runner-partner
        restart: always
        ports:
         - "8080:8080"
    notification:
        image: piggy1/notification:latest
        container_name: piggyback-dev-runner-notification
        restart: always
        ports:
         - "8080:8080"
    portal:
        image: piggy1/portal:latest
        container_name: piggyback-dev-runner-portal
        restart: always
        ports:
         - "5000:5000"