apiVersion: apps/v1
kind: Deployment
metadata:
  name: piggyback-notification-canary
  labels:
    app: piggyback-notification
    env: canary
  namespace: default
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  selector:
    matchLabels:
      app: piggyback-notification
      env: canary
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: piggyback-notification
        env: canary
    spec:
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-notification:v1
        name: piggyback-prod-runner-notification
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        restartPolicy: Always
        ports:
        - containerPort: 8086
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8086
        livenessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8086
          initialDelaySeconds: 30
          timeoutSeconds: 10
          failureThreshold: 1      
status: {}
