apiVersion: v1
kind: Service
metadata:
  labels:
    app: control-center
  name: control-center
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9021
  selector:
    app: control-center
  type: LoadBalancer
status:
  loadBalancer: {}