apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-invoice
  name: piggyback-invoice-service
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8084
  selector:
    app: piggyback-invoice
  type: LoadBalancer
status:
  loadBalancer: {}
