apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-location
  name: piggyback-location-service
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: piggyback-location
  type: LoadBalancer
status:
  loadBalancer: {}
