apiVersion: v1
kind: Service
metadata:
  name: piggyback-notification-service
spec:
  selector:
    app: piggyback-notification
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8086