apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-order
  name: piggyback-order-service
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8088
  selector:
    app: piggyback-order
  type: LoadBalancer
status:
  loadBalancer: {}
