apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-partner
  name: piggyback-partner-service
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8085
  selector:
    app: piggyback-partner
  type: LoadBalancer
status:
  loadBalancer: {}
