apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-portal
  name: piggyback-portal-service
  namespace: production
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: piggyback-portal
status:
  loadBalancer: {}