apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-user
  name: piggyback-user-service
  namespace: production
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8083
  selector:
    app: piggyback-user
status:
  loadBalancer: {}
