apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-user
  name: piggyback-user-service
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8083
  selector:
    app: piggyback-user
  type: LoadBalancer
status:
  loadBalancer: {}
