apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
status:
  loadBalancer: {}
