apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-notification
  name: piggyback-notification-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8086
  selector:
    app: piggyback-notification
  type: LoadBalancer
status:
  loadBalancer: {}
