apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-offers
  name: piggyback-offers-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8081
  selector:
    app: piggyback-offers
  type: LoadBalancer
status:
  loadBalancer: {}
