apiVersion: v1
kind: Service
metadata:
  labels:
    app: piggyback-portal
  name: piggyback-portal-service
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: piggyback-portal
  type: LoadBalancer
status:
  loadBalancer: {}
